name: it-compiles
run-name: Check compilation and source distribution
on:
    push:
        branches: [ "master" ]
        tags: "v[0-9]*"
    pull_request:
        branches: [ "master" ]
    workflow_dispatch:
jobs:
    make-distcheck:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - run: git show-ref
            - run: gem install --user-install asciidoctor
            - run: autoreconf --verbose --force --install --symlink
            - name: configure and make distcheck
              run: |
                PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
                export GIT_COMMITTER_NAME="$GITHUB_ACTOR_ID+$GITHUB_ACTOR"
                export GIT_COMMITTER_EMAIL="$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
                ./configure
                make distcheck
            - run: sudo apt-get update
            - run: sudo apt-get install build-essential debhelper asciidoc-base -y
            - name: make deb
              run: |
                export GIT_COMMITTER_NAME="$GITHUB_ACTOR_ID+$GITHUB_ACTOR"
                export GIT_COMMITTER_EMAIL="$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
                make deb
            - uses: actions/upload-artifact@v6
              with:
                  name: wd-security-${{ github.workflow }}.${{ github.run_number }}.${{ matrix.os }}
                  path: |
                      wd-security-*.tar.gz
                      wd-security_*
                      wd-security-dbgsym_*
                      libwd-security[0-9]_*
                      libwd-security[0-9]-dbgsym_*
                      libwd-security[0-9]-dev_*
                  compression-level: 0
    release:
        if: github.ref_type == 'tag'
        needs: make-distcheck
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
        runs-on: ${{ matrix.os }}
        steps:
            - run: sudo apt-get update
            - run: sudo apt-get install build-essential debhelper asciidoc-base -y
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - run: git show-ref
            - run: autoreconf --verbose --force --install --symlink
            - name: make deb
              run: |
                ./configure
                test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
                osdist=$(. "$os_release" && echo "${ID:?}")
                osver=$(. "$os_release" && echo "${VERSION_ID:?}")
                export EXTRA_VERSION="+$osdist-$osver"
                echo "EXTRA_VERSION: $EXTRA_VERSION"
                export GIT_COMMITTER_NAME="$GITHUB_ACTOR_ID+$GITHUB_ACTOR"
                export GIT_COMMITTER_EMAIL="$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
                make deb
            - name: publish release
              uses: softprops/action-gh-release@v2
              with:
                  name: WD Security for Linux ${{ github.ref_name }}
                  files: |
                      wd-security_*
                      wd-security-dbgsym_*
                      libwd-security[0-9]_*
                      libwd-security[0-9]-dbgsym_*
                      libwd-security[0-9]-dev_*
                  generate_release_notes: true
                  fail_on_unmatched_files: true
